### ISSUE TITLE
Error parsing script server/main.lua in resource esx_whitelistEnhanced:

### ISSUE THREAD

**Issue by FuTuRNeT** [ESX-Org/esx_whitelistEnhanced#13]
Hi, 
i have this error when i start my server.

Error parsing script server/main.lua in resource esx_whitelistEnhanced: server/main.lua:50: unexpected symbol near '7'
Failed to load script server/main.lua.

Can you help me please

Best Regards
Akram

**Comment by ElPumpo** [comment]
Fixed already.
