### ISSUE TITLE
Not waiting for async callback

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_whitelistEnhanced#18]
https://github.com/ESX-Org/esx_whitelistEnhanced/blob/7a0cee4bac9d1f6668c547a3a45c53b8026e65e9/server/main.lua#L287

**Comment by renaiku** [comment]
You mean the code under is executed ?
Yes, it's not in the callback part of the MySQL async fonction ^^

**Comment by ElPumpo** [comment]
Exactly, it doesn't wait for the async task to finish before it reloads the whitelist
