### ISSUE TITLE
queue not workin.

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_whitelistEnhanced#9]
queue is not workin for me. When there is 32/32 players there is just a massage server is full.

**Comment by SirMarkNL** [comment]
@JaroSound you need to stop resource hardcap. That's what causes this.

**Comment by JaroSound** [comment]
`citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/whitelist_sv.lua:213: bad argument #1 to 'remove' (position out of bounds)
stack traceback:
        [C]: in function 'table.remove'
        server/whitelist_sv.lua:213: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
`

After removing Hardcap, and i can join even if there is 32/32...

**Comment by ElPumpo** [comment]
Stop hardcap
